name: 'Branch Metadata'
description: 'Provides metadata information of a branch'
inputs:
  token:
    description: Github Token
    default: ${{ github.token }}
  repo:
    description: The owner and repository name. For example, Codertocat/Hello-World.
    default: ${{ github.repository }}
  path:
    description: Metadata file path to read. Default is `.github/branch-metadata.yml`.
    default: .github/branch-metadata.yml
  ref:
    description: The branch to provide the metadata.
    default: ${{ github.ref }}
  prop:
    description: The property key to return as output data, all metadata set of the branch will be return if not set.
outputs:
  data:
    description: The branch metadata described in .github/branch-metadata.yml
runs:
  using: 'node16'
  main: 'dist/index.js'
