name: 'AWS S3 Upload'
description: 'Upload a file to S3 bucket'
inputs:
  file:
    description: File path to upload. glob pattern is available.
    required: true
  region:
    description: AWS region
    default: ap-northeast-2
  bucket:
    description: Bucket name to which the PUT operation was initiated.
    required: true
  key:
    description: Object key for which the PUT operation was initiated. If not set, same name of file will be used.
  folder:
    description: Destination folder.
outputs:
  data:
    description: The response data from the successful upload.
runs:
  using: 'node16'
  main: 'dist/index.js'
